### ISSUE TITLE
Show swap space on device list

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#121]
The most frequent reason we have to restart F5s is when the memory and swap reach critical levels. If there is an iControl interface to query free/used memory/swap, it would sure be nice to show this on the device view.

In our environment, we end up rebooting F5s no more than once every couple months to clear memory leaks. BigIPReport could then highlight boxes with more than, say, 25% swap utilization?

**Comment by epacke** [comment]
Maybe make the thresholds configurable? Question, do you guys login through TMSH or Advanced shell? I've seen issues in the past where unfinished TMSH sessions has caused some serious swap usage.

**Comment by timriker** [comment]
Most people only have web access. Admins always use Advanced shell. I don't know anyone in our org that uses tmsh instead of advanced shell.

Yes, looking through our boxen, 25% is too low. Perhaps 50% or a configurable value.
