### ISSUE TITLE
dns lookup

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#122]
Seems I'm frequently doing dns lookups. It would be nice if we could integrate some kind of dns lookup in the UI. I don't know of a javascript way to do it though. An external DNS lookup might not fit the need as it the site is using split DNS, we probably want to see both internal and external results.

**Comment by timriker** [comment]
It might be nice to have a user supplied html snippet that would be included. ie: to add links at the top or bottom of the main page for navigation to side supplied tools which could include DNS lookups or other dashboards.

**Comment by epacke** [comment]
Maybe this could/should be done by javascript? We could include a hook that is executed at the end of the table render.

Regarding the DNS lookups, you can actually run this on a virtual server with iRules. Did it once to auto resolve dns to IP in firewall opening request forms using javascript:

https://clouddocs.f5.com/api/irules/DNS__query.html
