### ISSUE TITLE
(x) clear button on column search boxes

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#149]
In IE there is an "x" in the column search, but it's on top of the filter icon. In Chrome I don't see an "x" to clear a column search. Ideally, there would be a clear "x" in each filter column input when hovering over the field. It looks like this can be done using type="search" instead of type="text"

Alas, Edge does not fire "search" or "input" buttons on clicking the (x).
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/17584515/
Clicking someplace else triggers the update.

**Comment by timriker** [comment]
Alternate idea:
https://codepen.io/shidhincr/pen/ICLBD

**Comment by epacke** [comment]
That looks kind of nice actually.

**Comment by timriker** [comment]
Might turn off the filter background on other than .search::placeholder
Feel free to change it. :)
