### ISSUE TITLE
getMonitorRequestParameters does not parse headers for curl

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#154]
We're looking for '\\r\\n' instead of '\\\\r\\\\n'.

**Comment by timriker** [comment]
Hmm. It looks like either check might work. Perhap we should handle both? Testing.

**Comment by timriker** [comment]
Looks like there was a hot fix that caused the slashes to get duplicated. We'll fix them on our end. Reverting this part of the change.

**Comment by timriker** [comment]
Well, isn't this ugly. BIG-IP accepts either \r\n or \\r\\n and in the second case it looks like it adds another two \r\n lines in case the user forgot. Let's parse on either the Good \r\n or the Bad \\r\\n formats.

**Comment by epacke** [comment]
Ewwww, ugly indeed!
