### ISSUE TITLE
poll inactive node in pairs and fix up links

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#162]
We run high CPU on many of our clusters. Since the standby is in sync with the master, it would be faster to poll the standby and then fixup the links.
In out environment we have a master called lb-something-a and a slave lb-something-b and a dns entry for the float IP as just lb-something. It would be nice to fixup the links to just go to the active node, by hitting the float dns.

**Comment by epacke** [comment]
Not sure that I understand what you mean here. If you mean extracting the config/stats from the passive node it might not contain the latest config (most places does not use autosync in my experience). Also we would not get the correct stats.

Maybe I misunderstood though?

**Comment by timriker** [comment]
We do run autosync on all our clusters. Although the config should be the same on both nodes, you point out a valid issue that the stats would not be the same. I suppose we could cache config from the standby and stats from the active node. Not sure how much time we'd save.

**Comment by epacke** [comment]
My spontaneous thought would be that it would add overhead and complexity while not gaining so much. The calls to get the stats is the same as the ones that get pool and VIP information and those are the heavier ones I think?

**Comment by timriker** [comment]
Probably. I think I'll run some tests on our setup and try to get a feel for the potential gains. Our run takes around 25 minutes at present. Parallel polling might be accomplish more.

**Comment by epacke** [comment]
Moved:
https://github.com/net-utilities/BigIPReport/issues/14
