### ISSUE TITLE
REST: entries with different case broken

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#165]
Invoke-RestMethod does not handle mixed case json entries. If a rest service responds with:
`{ "key": "value", "KEY": "VALUE" }`
The response will fail to get converted and will end up as just a string. Having two virtual servers, pools, members, datagroup, profiles, etc. that are identical in name except for different case will trigger this issue. This is due to powershell trying to be case insensitive.

The work around I've found is to use:
`Invoke-WebRequest | ConvertFrom-Json -AsHashtable`
Which is only available in PowerShell 6. Windows 10 at present only includes Powershell 5.1

**Comment by epacke** [comment]
I'd say that this is likely not very common for people to have the same name on objects, but still...
This part is annoying about Powershell. They do so many things right, but stumble with the standards.

**Comment by timriker** [comment]
fix in 66750a919c9de746fe1ca3ca39a684411f4f3680
