### ISSUE TITLE
Issues running timriker code with RestAPI calls

### ISSUE THREAD

**Issue by sloanster4000** [epacke/BigIPReport#167]
After failing to get auth token I see this.
2020-01-10 08:43:10 10.1.34.74:Could not get auth token from IPADDRSSS
2020-01-10 08:43:11 Missing load balancer data, writing report anyway
The property 'LoadBalancer' cannot be found on this object. Verify that the property exists.
At C:\Users\esloan\Desktop\BigIPReport-timriker\BigIPReport-timriker\bigipreport.ps1:2142 char:1
+ $StatsMsg += " LB:" + $Global:ReportObjects.Values.LoadBalancer.Count
+ CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRecordException
+ FullyQualifiedErrorId : PropertyNotFoundStrict

I'm able to request an auth token successfully and pass it as a header in postman. 

I'm currently debugging the bigipreport.ps1 script but wanted to post an issue incase it was a version issue.

**Comment by timriker** [comment]
I'm normally testing with FQDNs, so the cert matches. I wonder if I need to do something to ignore the ssl cert. I'll test today.

**Comment by timriker** [comment]
added -SkipCertificateCheck throughout in case that's your issue. Try again?

**Comment by sloanster4000** [comment]
That resolved the issue I was seeing
