### ISSUE TITLE
Rest-Api Receive-Job (device name) error message

### ISSUE THREAD

**Issue by sloanster4000** [epacke/BigIPReport#168]
The following handled errors was thrown during the execution

Category | Linenumber | Line | Stacktrace
-- | -- | -- | --
PropertyNotFoundException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at Get-LTMInformation, :   line 1011 at GetDeviceInfo, : line 1712 at , :   line 1745
HttpResponseException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1682 at , : line 1745
PropertyNotFoundException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1632 at , : line 1745
PropertyNotFoundException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at Get-LTMInformation, :   line 1011 at GetDeviceInfo, : line 1712 at , :   line 1745
HttpResponseException | 1771 | At C:\inetpub\bigipreport\bigipreport.ps1:1771   char:17 + $lines=Receive-Job -Job $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1630 at , : line 1745
HttpResponseException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1622 at , : line 1745
HttpResponseException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1622 at , : line 1745
HttpResponseException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1622 at , : line 1745
PropertyNotFoundException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at Get-LTMInformation, :   line 1011 at GetDeviceInfo, : line 1712 at , :   line 1745
HttpResponseException | 1771 | At C:\inetpub\bigipreport\bigipreport.ps1:1771   char:17 + $lines=Receive-Job -Job $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1682 at , : line 1745
HttpResponseException | 1771 | At   C:\inetpub\bigipreport\bigipreport.ps1:1771 char:17 + $lines=Receive-Job -Job   $job + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ | at GetDeviceInfo, :   line 1622 at , : line 1745

**Comment by sloanster4000** [comment]
As a note I switched from IP's to hostnames

**Comment by timriker** [comment]
can you try running against the one machine?
./bigipreport.ps1 example.xml loadbalancer.example.com

**Comment by sloanster4000** [comment]
When I run it with just one listed no issues. By introducing a second I see the issue. You thinking we have a race condition going on here?

**Comment by timriker** [comment]
I'm trying to expose the errors from the child to the parent process, but it's not working so far. You see the child errors reported when the parent tries a Receive-Job call. The error gets reported on that line, and not on the original line. Kind of a pain. :(

**Comment by sloanster4000** [comment]
In the current state when these errors happen, it generates an email error notification and the end user would be unsure how to resolve. == not useful error message.

**Comment by timriker** [comment]
I agree. The forked model does not effectively capture the errors/warnings in the child processes. I've tried a number of things, but still not really happy with it. :(

**Comment by timriker** [comment]
I'm handling some errors explicitly now. It's better, but we likely still have a ways to go.
