### ISSUE TITLE
SOAP branch: REST calls for ASM and datagroups fail. Suspect cert issue.

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#174]
We might not be ignoring unmatching certificates for REST calls to get ASM and datagroups in v5.3.1 like we are in my REST only branch.
Probably need to add -SkipCertificateCheck to Invoke-RestMethod and Invoke-WebRequest calls.

**Comment by epacke** [comment]
I don't like it, but I also think we should do this. Far too many don't have a valid PKI.

**Comment by timriker** [comment]
The REST ( now master ) branch ignores certificates. I don't like this, but it seems common practice is self signed certs. We use the same wildcard cert that we use externally.

The SOAP branch uses REST calls for ASM and datagroups. I don't know if it ignores certs. I don't have an F5 with invalid certs to test on at the moment.

**Comment by epacke** [comment]
Since the master branch ignores certs we can close this one?

**Comment by timriker** [comment]
It this still exists, it would affect the SOAP branch only.
