### ISSUE TITLE
Errors when iRules disabled 

### ISSUE THREAD

**Issue by jo-xxx** [epacke/BigIPReport#183]
With configuration 

```
<iRules>
            <Enabled>false</Enabled>
            <ShowiRuleLinks>false</ShowiRuleLinks>
            <ShowDataGroupLinks>false</ShowDataGroupLinks>
</iRules>
```
the following errors occur: 

- Lines
1915: `log verbose "iRule links disabled in config. Writing empty json object to $($Global:irules + ".tmp")"`
1917: `$StreamWriter = New-Object System.IO.StreamWriter($($Global:irules + ".tmp"), $false, $Utf8NoBomEncoding,0x10000)"`
throw errors because $Global:irules is not defined. Should be $Global:paths.irules.

- Line 
1920: `$RuleScope = $Global:Out.iRules | Where-Object { $_.name -in $Bigipreportconfig.Settings.iRules.iRule.iRuleName -and $_.loadbalancer -in $Bigipreportconfig.Settings.iRules.iRule.loadbalancer }`
throws error because configuration file does not include settings for  $Bigipreportconfig.Settings.iRules.iRule.iRuleName and $Bigipreportconfig.Settings.iRules.iRule.loadbalancer.

**Comment by timriker** [comment]
Thanks! I have not tested with this disabled in a while. :)
I also removed some comments pointing to the old data structures.

**Comment by jo-xxx** [comment]
Solved. Thanks
