### ISSUE TITLE
Convert the javascript to typescript

### ISSUE THREAD

**Issue by epacke** [epacke/BigIPReport#195]
Moving module break-outs to different issue to keep the change scope moderate

**Comment by timriker** [comment]
No strong preference. The Typescript overhead is not seen by the browser. I like being able to test in underlay/ without a build step. I would hope we can keep that.

**Comment by epacke** [comment]
It'd require two commands, one for file watch and transpile when the code is changed, and one that monitors when the resulting js file is changed. Does that sound acceptable?

**Comment by timriker** [comment]
in the string-interpolation the ps1 has:
}
else {
formatting.

Also I'm still on Ubuntu 18.04 so node and npm are older than eslint expects.

**Comment by epacke** [comment]
I think you can install a newer version manually if it poses an issue. Or I can fix a docker container for linting. :)
