### ISSUE TITLE
Make the error reporting a bit more specific

### ISSUE THREAD

**Issue by epacke** [epacke/BigIPReport#65]
Right now it says that the report generation failed when the passive load balancer isn't responding.

**Comment by timriker** [comment]
Is this fixed? We do better reporting now, and have the option to write a report anyway.

**Comment by epacke** [comment]
I like the write report anyway feature.

But I would say that the ideal solution for me at least would be to alert that the active one fails and then revert to the passive load balancer. Takes a bit more logic, but it'd give us data most of the time.  Not sure if this is the case?

**Comment by timriker** [comment]
I'd like to add an "Errors: <n>" to the footer.

Yes, it would be nice to handle polling from a passive node if the active node fails to pool. The parallel processing makes this a bit complicated.
