### ISSUE TITLE
Enhancement: limit pool status requests

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#75]
It would be nice to have a limit to how many pool requests can be processed. If the user has more than x pools open on screen, stop polling and show a "paused" header at the top. In our configuration, we have thousands of pools on many different F5s. It's easy to set your preferences to "expand all pool members"  and then select "All" for visible rows. This then sends thousands of pool status requests.

I realize that a preference trusts the user to not do bad things, and anyone could still run thousands of pool status requests themselves. I'm just trying to encourage good behaviour not actually enforce it.

There is already a setting for simultaneous pool requests "MaxQueue" and a time "RefreshRate" it would be nice to have a "MaxReqests" or similar.

**Comment by epacke** [comment]
Good idea!
