### ISSUE TITLE
shrink PoolMembers text if duplicated

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#77]
If $PoolNamePort is the same as $MemberIPPort it would be nice to just show one instead of both with a dash between them.

Most of our pool members are just the IPs as the F5 does not allow easy renaming of names when DNS changes happen.

**Comment by epacke** [comment]
Show me an example of how you'd like it to look like?

**Comment by timriker** [comment]
if the pool member currently shows as:
10.1.2.3:80 - 10.1.2.3:80 - <icon>
instead just show:
10.1.2.3:80 - <icon>

**Comment by epacke** [comment]
We use the server name as name of the node. This is relevant information imho. Proposing to close this issue? What do you think?

**Comment by timriker** [comment]
I was only proposing shrinking them if they are exact duplicates. They almost always are duplicates where I work now, but at many sites the name is something other than the IP and so displaying both makes sense.

**Comment by epacke** [comment]
I both agree and disagree here. In one way it's better to keep it for consistency across the report. However, showing the same information twice looks buggy. Especially since name and IP is not properly distinguished as ie. a column. Let's add this to the to-do list too. :)
