### ISSUE TITLE
link in pool member table

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#78]
It would be nice if in the pool member details view in addition to the HTTP link, or perhaps instead of the HTTP link, there was a link that opened in a new window. (target="_blank")

**Comment by epacke** [comment]
I considered this too, but somehow it felt better to let the user actively copy the link, amend whatever is needed and then test it. Otherwise I might have had people who barely knows what an HTTP link is clicking on stuff and then complaining that it did not work. 

But you have a good point.

**Comment by timriker** [comment]
Similar comment here. I'm hoping that users have more than the average level of knowledge here. Perhaps my expectations are too high. :)

**Comment by epacke** [comment]
Depends on the company. Is there also a gain in terms of UX by having the buttons behave the same way? I guess there's no harm to add an onClick event to it as well as the text popup. What do you think?

**Comment by timriker** [comment]
I'd rather have it there and not use it, then wish it was there and not have it. :)

**Comment by epacke** [comment]
Good point!
