### ISSUE TITLE
tcp half open checks on standard ports

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#79]
It would be nice to have HTTP, CURL, and Netcat links populated on TTYPE_TYPE_HALF_OPEN checks where the target is on 80, 443, and perhaps other common ones like 8080, 8000, 8443. 443 and 8443 would assume SSL unless that can be computed by the pool usage elsewhere.

**Comment by epacke** [comment]
How would the tests look like in the HTTP and Curl links? I've seen a few cases of tcp monitors with send and receive strings and that would work in netcat, but not sure how to implement it with HTTP and Curl? I've deliberately avoided things that only works in some cases.

What do you think?

**Comment by timriker** [comment]
I understand your concern. Having a link there to a GET / request might not work. Especially when the pool member is not even an http service. My perspective is that the BIG-IP Report user should know that, and expect following the link to not work. I would hope that the link was there in case it happened to work. I don't need to use it, but I can if it's there.

**Comment by sloanster4000** [comment]
At a minimum I think a netcat to that server and port would be doing the same thing as a tcp-half. Curl or http I'm on the fence but netcat makes sense to me.

**Comment by epacke** [comment]
Agreed. Let's add netcat to tcp monitors.
