### ISSUE TITLE
Include all iRules

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#80]
Is there a way to include all iRules on the iRule screen? Something like this?

```
<iRules>
	<iRule>
		<Loadbalancer>*</Loadbalancer>
		<iRuleName>*</iRuleName>
	</iRule>
</iRules>
```

**Comment by epacke** [comment]
Could you please share a scenario where this would be useful as opposed to going via virtual servers? So far I've only kept this feature for legacy reasons.

**Comment by timriker** [comment]
Sometimes a rule is not attached currently. Most often it's just remembering which servers use it and which do not. It's not a show stopper. Long term it might be nice to be able to search all irules or even search all pools. The default view by virtual server is awesome. I'm picturing alternate entries to answer things like "what virtual servers uses this iRule?".
This is not a high priority request, just a nice to have. :)

**Comment by epacke** [comment]
Agreed, in some cases it'd be nice to have.

**Comment by timriker** [comment]
The iRule view includes all rules in my fork.
