### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#86]
Would be nice to include a favicon.ico that has the F5 logo

**Comment by MikeyPerez** [comment]
I include our company logo at this point, nice thought on F5 being used. Also change the <title> as we separate reports per environment.

You can create the icon file then add HTML to the .ps1 file right after this section until it gets included in a release.

[void]$Global:HTML.AppendLine(@'
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>BIG-IP Report</title>
                _**<link rel='shortcut icon' href='favicon.ico' type='image/x-icon'/ >**_

**Comment by MikeyPerez** [comment]
that did not show correctly. Here is the line

<link rel='shortcut icon' href='favicon.ico' type='image/x-icon'/ >

**Comment by MikeyPerez** [comment]
learning. Need to use the "Insert Code" function :)

`[void]$Global:HTML.AppendLine(@'
<!DOCTYPE html>
<html lang="en">
	<head>
		<title>WTW BIG-IP Report</title>
        <link rel='shortcut icon' href='favicon.ico' type='image/x-icon'/ >`

**Comment by MikeyPerez** [comment]
Wow, 5th attempt. Paste the line below in between < >

link rel='shortcut icon' href='favicon.ico' type='image/x-icon'/

**Comment by epacke** [comment]
I wonder, if we should not have a BigIP Report specific icon here? Otherwise we might mix the report with the F5 Web UI when managing devices?

**Comment by epacke** [comment]
We can still use a version of it, but with some small tweak. Not sure how F5 will react in terms of copyright though. Big companies is not always rational on that front.

**Comment by epacke** [comment]
Added a favicon from iconfinder.
