### ISSUE TITLE
Project license and script license don't match

### ISSUE THREAD

**Issue by sloanster4000** [epacke/BigIPReport#87]
The project shows licenses by MIT but Bigipreport.ps1 references GPL at the top.
Which one should be used?

I'm in favor of just MIT.. should I pull and submit a change?

**Comment by epacke** [comment]
Gotta say: You forced me to read up on licenses. Not sure what to do here.

I definitely don't want anyone to sell BigIP Report for profit, which MIT allows. At the same time I don't want people changing small things to be forced to publish them. You probably know more than I do here. Is there a license that would cover these things?

**Comment by epacke** [comment]
GPL sounds like what I want. Do you want to make a PR?

**Comment by sloanster4000** [comment]
PR created to fix this issue.
