### ISSUE TITLE
Statistics

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#90]
Add somewhere, probably under Console, perhaps a new tab called "Statistics" some of the following:
last update date/time
number of virtual hosts, pools, irules
load time? render time?
some stats on pool status calls since last page reload?

**Comment by MikeyPerez** [comment]
Would it be possible to update Pool Member - Current Connections and Max Connections as part of the Status VIP polling irule?

**Comment by timriker** [comment]
Once I get my dynamic rendering working, I plan to look into the iRule to try to get it to export in the same format as an entry in pools.json so we can just replace the pools entry in memory and re-render that table.

**Comment by timriker** [comment]
I added some stats to the log in my fork so it shows vs, irule, pools, dg counts.

I have not found a way to access current connections or max connections from an iRule, so it might not be possible to have the polling update that. :(
