### ISSUE TITLE
load datatables from json

### ISSUE THREAD

**Issue by timriker** [epacke/BigIPReport#91]
Loading virtualhosts from json using a datatables ajax source is much faster. Much html rendering would need to be done in javascript. Here's a basic view that loads in seconds with our large configs.

https://pastebin.com/v1wPmdFA

Just drop it in your output file as test.html or whatever and it will load resources from json/ js/ css/ etc.

**Comment by timriker** [comment]
I have much of this working now on my branch. Still working on generating pool tables. Load times are incredibly different. 10 seconds vs over five minutes.

**Comment by timriker** [comment]
I've still got a ways to go to make it useful. Working on filling in pool information now. The ASM policy type is filled in from the html building code that I've nuked. I'm trying to decide if I should create a new asm.json to dump that data to disk. Thoughts?
My datatables headings are now in the bigipreport.js and don't change if ASM is present or not, so currently if you run my version against a box without ASM, it still creates an ASM column.

**Comment by sloanster4000** [comment]
This is a huge gain. I've been working with Tim on this and the difference is huge.

Thoughts on merging this in?
